-- Showcase: Personalizable YouTube Clone — initial schema
-- Migration 0001: sites, visitors, preferences, chat_turns
-- Append-only. Never edit this file after merge; create 0002_*.sql instead.

create extension if not exists "pgcrypto";

create table if not exists sites (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  base_config jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists visitors (
  id uuid primary key,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  user_agent text
);

create table if not exists preferences (
  id uuid primary key default gen_random_uuid(),
  visitor_id uuid not null references visitors(id) on delete cascade,
  site_id uuid not null references sites(id) on delete cascade,
  patch jsonb not null,
  rationale text,
  message_id text,
  created_at timestamptz not null default now()
);
create index if not exists preferences_visitor_site_created_idx
  on preferences(visitor_id, site_id, created_at);

create table if not exists chat_turns (
  id uuid primary key default gen_random_uuid(),
  visitor_id uuid not null references visitors(id) on delete cascade,
  site_id uuid not null references sites(id) on delete cascade,
  user_message text not null,
  assistant_message text,
  tool_uses jsonb,
  cost_usd numeric,
  cache_hit_ratio numeric,
  input_tokens integer,
  output_tokens integer,
  cache_read_tokens integer,
  cache_creation_tokens integer,
  duration_ms integer,
  created_at timestamptz not null default now()
);
create index if not exists chat_turns_visitor_site_created_idx
  on chat_turns(visitor_id, site_id, created_at desc);

-- On-demand catalog growth: extra videos generated by request_more_content
-- live in a separate table so the base catalog stays canonical and small.
create table if not exists generated_videos (
  id text primary key,
  site_id uuid not null references sites(id) on delete cascade,
  category text not null,
  data jsonb not null,
  created_at timestamptz not null default now()
);
create index if not exists generated_videos_site_category_idx
  on generated_videos(site_id, category);
